#!/bin/bash

ip link set eth0 up

ip a a 5.5.5.66/26 dev eth0

ip link set eth1 up

ip a a 5.5.5.130/26 dev eth1

ip route add 5.5.5.0/26 via 5.5.5.65

ip route add 192.168.4.0/25 via 5.5.5.65

ip route add 5.5.5.192/26 via 5.5.5.129


